[package]
name = "ethereum-client"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }

ethers = "2.0.14"
serde = { version = "1.0.217", features = ["derive"] }