[ethereum]
rpc_url = "https://rpc.gnosischain.com"

[contracts]
balancer_pool = "0x1acd5c5e69dc056649d698046486fb54545ce7e4"
gauge_addr = "0xbcF4969d4dc6Cb86Ce0B8a101d220b558F14739C"

[kafka]
brokers = "localhost:9094"
topic = "ethereum-logs"
